name: Mirror DockerHub

on:
  schedule:
    - cron: '0 22 8,23 * *'
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: 'The name of Image to be Mirrored'
        type: choice
        options:
          - ''
          - 'buildkit'
          - 'maven'
          - 'eclipse-temurin'
          - 'golang'
          - 'node'
          - 'nginx'
          - 'dotnet-sdk'
          - 'plugin-docker-buildx'
          - 'plugin-dockle'
          - 'plugin-extend-env'
          - 'plugin-kaniko'
          - 'plugin-node-pm'
          - 'plugin-sonarqube-scanner'
          - 'plugin-dependency-check'
          - 'plugin-trivy'
          - 'plugin-woodpecker-rsync'
          - 'plugin-drone-rsync'
          - 'plugin-golangci-lint'
        default: ''
      MULTI_ARCH:
        description: 'Control what is copied if source-image refers to a multi-architecture image.'
        type: choice
        options:
          - ''
          - 'system'
          - 'all'
          - 'linux/amd64'
          - 'linux/arm64'
          - 'linux/amd64,linux/arm64'
        default: ''

env:      
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        include:
          - name: buildkit
            repo: docker.io
            image: moby/buildkit
            multi-arch: system
          - name: maven
            repo: docker.io
            image: maven
            multi-arch: system
          - name: eclipse-temurin
            repo: docker.io
            image: eclipse-temurin
            multi-arch: 'linux/amd64,linux/arm64'
          - name: golang
            repo: docker.io
            image: golang
            multi-arch: system
          - name: node
            repo: docker.io
            image: node
            multi-arch: 'linux/amd64,linux/arm64'
          - name: nginx
            repo: docker.io
            image: nginx
            multi-arch: 'linux/amd64,linux/arm64'
          - name: dotnet-sdk
            repo: mcr.microsoft.com
            image: dotnet/sdk
            dest-image: dotnet/sdk
            multi-arch: system
          - name: plugin-docker-buildx
            repo: codeberg.org
            image: woodpecker-plugins/docker-buildx
            dest-image: woodpecker-plugins/plugin-docker-buildx
            multi-arch: system
          - name: plugin-dockle
            repo: docker.io
            image: euryecetelecom/woodpeckerci-dockle
            dest-image: woodpecker-plugins/plugin-dockle
            multi-arch: system
          - name: plugin-extend-env
            repo: docker.io
            image: woodpeckerci/plugin-extend-env
            dest-image: woodpecker-plugins/plugin-extend-env
            multi-arch: system
          - name: plugin-kaniko
            repo: docker.io
            image: woodpeckerci/plugin-kaniko
            dest-image: woodpecker-plugins/plugin-kaniko
            multi-arch: system
          - name: plugin-node-pm
            repo: codeberg.org
            image: woodpecker-plugins/node-pm
            dest-image: woodpecker-plugins/plugin-node-pm
            multi-arch: system
          - name: plugin-sonarqube-scanner
            repo: docker.io
            image: plugins/sonarqube-scanner
            dest-image: woodpecker-plugins/plugin-sonarqube-scanner
            multi-arch: system
          - name: plugin-dependency-check
            repo: docker.io
            image: owasp/dependency-check
            dest-image: woodpecker-plugins/plugin-dependency-check
            multi-arch: system
          - name: plugin-trivy
            repo: codeberg.org
            image: woodpecker-plugins/trivy
            dest-image: woodpecker-plugins/plugin-trivy
            multi-arch: system
          - name: plugin-woodpecker-rsync
            repo: docker.io
            image: misotolar/woodpecker-rsync
            dest-image: woodpecker-plugins/plugin-rsync
            multi-arch: system
          - name: plugin-drone-rsync
            repo: docker.io
            image: drillster/drone-rsync
            dest-image: woodpecker-plugins/plugin-drone-rsync
            multi-arch: system
          - name: plugin-golangci-lint
            repo: docker.io
            image: golangci/golangci-lint
            dest-image: woodpecker-plugins/plugin-golangci-lint
            multi-arch: system
    steps:
      - uses: actions/checkout@v7
        if: ${{ github.event.inputs.IMAGE_NAME == '' || github.event.inputs.IMAGE_NAME == matrix.name }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        if: ${{ github.event.inputs.IMAGE_NAME == '' || github.event.inputs.IMAGE_NAME == matrix.name }}
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Log in to My Gitea
        uses: docker/login-action@v4
        if: ${{ github.event.inputs.IMAGE_NAME == '' || github.event.inputs.IMAGE_NAME == matrix.name }}
        with:
          registry: ${{ secrets.GITEA_SERVER }}
          username: ${{ secrets.GITEA_USERNAME }}
          password: ${{ secrets.GITEA_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        if: ${{ github.event.inputs.IMAGE_NAME == '' || github.event.inputs.IMAGE_NAME == matrix.name }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up skopeo environment
        uses: warjiang/setup-skopeo@main
        if: ${{ github.event.inputs.IMAGE_NAME == '' || github.event.inputs.IMAGE_NAME == matrix.name }}
        with:
          version: latest

      - name: Fix skopeo PATH and permissions
        if: ${{ github.event.inputs.IMAGE_NAME == '' || github.event.inputs.IMAGE_NAME == matrix.name }}
        run: |
          install -D -m 755 ./skopeo "$HOME/.local/skopeo-bin/skopeo"
          echo "$HOME/.local/skopeo-bin" >> "$GITHUB_PATH"
          echo 'unqualified-search-registries = ["docker.io"]' | sudo tee /etc/containers/registries.conf

      - name: 'Skopeo copy images to My Gitea'
        if: ${{ github.event.inputs.IMAGE_NAME == '' || github.event.inputs.IMAGE_NAME == matrix.name }}
        run: |
          skopeo --version
          
          # Check the value of MULTI_ARCH
          ARCH_VAL="${{ github.event.inputs.MULTI_ARCH || matrix.multi-arch || 'system' }}"
          
          # Determine whether to append additional parameters
          EXTRA_ARGS=""
          if [ "$ARCH_VAL" != "all" ] && [ "$ARCH_VAL" != "system" ]; then
            EXTRA_ARGS="--strip-removed-platforms --remove-list-signatures"
          fi
                    
          for tag in $(cat ./images/${{ matrix.name }}); do
            echo "${{ matrix.dest-image || matrix.image }}:$tag" / "$ARCH_VAL"
            skopeo copy --multi-arch "$ARCH_VAL" $EXTRA_ARGS \
              docker://${{ matrix.repo }}/${{ matrix.image }}:$tag \
              docker://${{ secrets.GITEA_SERVER }}/${{ secrets.GITEA_REPOSITORY }}/${{ matrix.dest-image || matrix.image }}:$tag
          done
