name: Copy Image From DockerHub to Somewhere Manually

on:
  workflow_dispatch:
    inputs:
      SOURCE_REGISTRY:
        description: 'Source Container Registry'
        required: true
        default: 'docker.io'
      SOURCE_IMAGE_FULL_NAME:
        description: 'Source Image Full Name with Repository and Tag'
        required: true
        default: ''
      TARGET_REGISTRY:
        description: 'Target Container Registry'
        required: true
        default: ''
      TARGET_REPOSITORY:
        description: 'Target Container Repository'
        required: true
        default: ''
      TARGET_IMAGE_NAME:
        description: 'Target Image Name with Tag'
        required: true
        default: ''
      MULTI_ARCH:
        description: 'Multi-Arch support for skopoe-copy'
        type: choice
        required: true
        options:
          - 'all'
          - 'system'
          - 'linux/amd64'
          - 'linux/arm64'
          - 'linux/amd64,linux/arm64'
        default: 'system'

jobs:
  skopeo-copy:
    name: Copy Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v7
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Log in to My Gitea
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.GITEA_SERVER }}
          username: ${{ secrets.GITEA_USERNAME }}
          password: ${{ secrets.GITEA_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up skopeo environment
        uses: balena-io-experimental/setup-skopeo-action@main
        with:
          version: latest

      - name: 'Skopeo copy images to Target Container '
        run: |
          # Compatible with the latest Podman configuration
          echo 'unqualified-search-registries = ["docker.io"]' | sudo tee /etc/containers/registries.conf
          
          skopeo --version
          
          # Check the value of MULTI_ARCH and determine whether to append additional parameters
          MULTI_ARCH_VAL="${{ github.event.inputs.MULTI_ARCH || 'system' }}"
          
          # Determine whether to append additional parameters
          EXTRA_ARGS=""
          if [ "$MULTI_ARCH_VAL" != "all" ] && [ "$MULTI_ARCH_VAL" != "system" ]; then
            EXTRA_ARGS="--strip-removed-platforms --remove-list-signatures"
          fi
          
          skopeo copy --multi-arch "$MULTI_ARCH_VAL" $EXTRA_ARGS \
            docker://${{ github.event.inputs.SOURCE_REGISTRY }}/${{ github.event.inputs.SOURCE_IMAGE_FULL_NAME }} \
            docker://${{ github.event.inputs.TARGET_REGISTRY || secrets.GITEA_SERVER }}/${{ github.event.inputs.TARGET_REPOSITORY || secrets.GITEA_REPOSITORY }}/${{ github.event.inputs.TARGET_IMAGE_NAME }}

